Repository rauc/meta-rauc-community, pull requests merged in 2025-02, with the labels that each got.

#140 beaglebone: linux: remove redundant rauc.cfg
  meta-rauc-beaglebone/recipes-kernel/linux/files/rauc.cfg
  meta-rauc-beaglebone/recipes-kernel/linux/linux-yocto_%.bbappend
Labels: cleanup

#142 nxp: minor updates and fixes for README.rst
  meta-rauc-nxp/README.rst
Labels: documentation

#145 qemuarm: Add support for aarch64 and make it the default
  meta-rauc-qemuarm/README.rst
  meta-rauc-qemuarm/kas-qemuarm.yml
  meta-rauc-qemuarm/recipes-bsp/u-boot/files/boot.cmd.in
  meta-rauc-qemuarm/recipes-bsp/u-boot/u-boot_%.bbappend
  meta-rauc-qemuarm/recipes-core/images/core-image-minimal.bbappend
  meta-rauc-qemuarm/recipes-core/rauc/files/system.conf
  meta-rauc-qemuarm/recipes-kernel/linux/files/qemuarm64.dts
  meta-rauc-qemuarm/recipes-kernel/linux/linux-yocto_%.bbappend
Labels: enhancement
